# Configuration file for Jupyter notebook dependencies.
#
# This file is used to install dependencies necessary to run the Jupyter
# notebook tutorials in the documentation. It is currently used for
#
# - Interactive tutorials using Binder:
#   https://mybinder.readthedocs.io/en/latest/using/config_files.html
name: jupyter-tutorials-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pip:
    - -r docs/notebook-requirements.txt
    - -e .
