# Workflow which runs all Jupyter notebooks of the documentation and fails on errors.
name: Run Jupyter notebooks

on:
  # Triggers the workflow on push or pull request
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          environment-file: environment.yml

      - name: Execute all notebooks with nbconvert
        run: |
          conda install nbconvert
          for file in $(find -wholename "./docs/source/**/*.ipynb" -not -path "**/.ipynb_checkpoints/*")
          do
              jupyter nbconvert --to notebook --execute --debug $file
          done
